version: '3'
services:
  docker_jenkins:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: 'miragesu/jenkins-phabricator'
    container_name: jenkins
    ports:
      - '80:8080'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/data/jenkins/jenkins_home:/var/jenkins_home
      - /home/v1.0-beta8_nogit/:/git_spx_plugin
