version: '3'
services:
  docker_jenkins:
    restart: always
    image: 'miragesu/jenkins-phabricator:latest'
    container_name: docker_jenkins
    ports:
      - '80:8080'
      - '50000:50000'
    volumes:
      - /data/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
